name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    # Suurendatud ressursid parema jõudluse jaoks
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --ipc=host
    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisites
      run: apt-get update && apt-get install -y unzip
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Create .env file for testing
      run: |
        cat > .env << EOF
        JWT_SECRET=test-jwt-secret-for-ci-cd-environments-only
        MAILGUN_API_KEY=test-mailgun-api-key
        MAILGUN_DOMAIN=test.example.com
        PORT=3000
        NODE_ENV=test
        EMAIL_TEST_MODE=true
        DEBUG=false
        EOF
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        # Suurendatud timeoutid GitHub Actions keskkonnas
        export PLAYWRIGHT_TEST_TIMEOUT=60000
        export PLAYWRIGHT_ACTION_TIMEOUT=30000
        export PLAYWRIGHT_NAVIGATION_TIMEOUT=30000
        # Vähenda paralleelsust ja koormat
        bun run test --workers=1
      env:
        HOME: /root
        CI: 'true'
        DEBUG_CLEANUP: 'true'
    - name: Ensure playwright-report directory exists
      run: mkdir -p playwright-report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30